Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -25,18 +25,17 @@ jobs:
       - name: Get SonarCloud quality gate status
         env:
           SONAR_TOKEN1: ${{ secrets.SONAR_TOKEN1 }}
-      run: |
-        RESULT=$(curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=GIGXPad-com_xpad-web-v2&analysisId=$SONAR_ANALYSIS_ID")
-        STATUS=$(echo $RESULT | jq -r .status)
-        echo $STATUS
-        - name: Check quality gate status
+        run: |
+          RESULT=$(curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=GIGXPad-com_xpad-web-v2&analysisId=$SONAR_ANALYSIS_ID")
+          STATUS=$(echo $RESULT | jq -r .status)
+          echo $STATUS
+      - name: Check quality gate status
         if: ${{ env.STATUS == 'ERROR' }}
         run: |
-        echo "Quality gate status is ERROR"
-        exit 1
+          echo "Quality gate status is ERROR"
+          exit 1
   checkout_build:
       runs-on: ubuntu-latest
-
       steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -65,39 +64,39 @@ jobs:
       runs-on: ubuntu-latest
       environment: production
       steps: 
-      - name: Download JAR file
-        uses: actions/download-artifact@v2
-        with:
-          name: app-jar
-          path: target
+        - name: Download JAR file
+          uses: actions/download-artifact@v2
+          with:
+            name: app-jar
+            path: target
 
-      - name: Build Docker image
-        run: docker build -t 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot .
+        - name: Build Docker image
+          run: docker build -t 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot .
 
-      - name: Install and configure AWS CLI
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip -q awscliv2.zip
-          sudo ./aws/install --update
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws configure set default.region me-central-1
+        - name: Install and configure AWS CLI
+          run: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip -q awscliv2.zip
+            sudo ./aws/install --update
+            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws configure set default.region me-central-1
 
-      - name: Login to ECR
-        run: |
-          aws ecr get-login-password --region me-central-1 | docker login --username AWS --password-stdin 590733205684.dkr.ecr.me-central-1.amazonaws.com
+        - name: Login to ECR
+          run: |
+            aws ecr get-login-password --region me-central-1 | docker login --username AWS --password-stdin 590733205684.dkr.ecr.me-central-1.amazonaws.com
 
-      - name: Tag and push Docker image
-        run: |
-          docker tag 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:latest 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}
-          docker push 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}
+        - name: Tag and push Docker image
+          run: |
+            docker tag 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:latest 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}
+            docker push 590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}
 
-      - name: Deploy to EKS
-        run: |
-          aws eks update-kubeconfig --region me-central-1 --name rakbank
-          mkdir -p k8s
-          export ECR_REPOSITORY_URL="590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}"
-          envsubst < k8s-deployment.yaml > k8s/k8s-deployment.yaml
-          echo "resources:" > k8s/kustomization.yaml
-          echo "- k8s-deployment.yaml" >> k8s/kustomization.yaml
-          kubectl kustomize k8s | kubectl apply -f - --force
+        - name: Deploy to EKS
+          run: |
+            aws eks update-kubeconfig --region me-central-1 --name rakbank
+            mkdir -p k8s
+            export ECR_REPOSITORY_URL="590733205684.dkr.ecr.me-central-1.amazonaws.com/springboot:${GITHUB_SHA}"
+            envsubst < k8s-deployment.yaml > k8s/k8s-deployment.yaml
+            echo "resources:" > k8s/kustomization.yaml
+            echo "- k8s-deployment.yaml" >> k8s/kustomization.yaml
+            kubectl kustomize k8s | kubectl apply -f - --force
